# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: voipbin_client
generate:
  models: true
  client: true
output-options:
  skip-prune: true
